[package]
name = "tower-http-gateway-service"
version = "0.1.0"
edition = "2021"
description = "Middleware that implements an Tower HTTP gateway / reverse proxy"
license = "MIT"

[dependencies]
bytes = "1"
http = "0.2.7"
pin-project-lite = "0.2.7"
tower-layer = "0.3"
tower-service = "0.3"
